version: 2

builds:
  - id: buildkite-gha-linux
    main: ./cmd/buildkite-gha
    binary: buildkite-gha
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: buildkite-gha-launcher-linux
    main: ./cmd/buildkite-gha-launcher
    binary: buildkite-gha-launcher
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64]
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: buildkite-gha
    ids: [buildkite-gha-linux]
    formats: [tar.gz]
    name_template: buildkite-gha_Linux_x86_64
    builds_info:
      mtime: "{{ .CommitDate }}"
      owner: root
      group: root
    files:
      - src: LICENSE
        info:
          mtime: "{{ .CommitDate }}"
          mode: 0644
          owner: root
          group: root
  - id: buildkite-gha-launcher
    ids: [buildkite-gha-launcher-linux]
    formats: [binary]
    name_template: buildkite-gha-launcher_Linux_x86_64

checksum:
  name_template: checksums.txt

release:
  name_template: "{{ .Tag }}"
  target_commitish: "{{ .Commit }}"
  use_existing_draft: true
  replace_existing_artifacts: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs(?:\\([^)]*\\))?:"
      - "^test(?:\\([^)]*\\))?:"
      - "^chore(?:\\([^)]*\\))?:"
      - "^ci(?:\\([^)]*\\))?:"
      - "^Merge "
