agents:
  queue: "hosted"

steps:
  - label: ":pipeline: Experimental runner user importer"
    key: "experimental-runner-user-importer"
    timeout_in_minutes: 20
    retry:
      automatic: false
    plugins:
      - github-actions#v0.9.3:
          workflow: .github/workflows/experimental-runner-user.yml
          source-ref: 1f40c890725ae21d2a523b031167c57141f85b4e
          experimental-runner-user: true
          runners:
            - runs-on: ubuntu-latest
              queue: hosted

  - label: ":pipeline: Experimental runner user continuation loader"
    key: "experimental-runner-user-continuation-loader"
    depends_on: "experimental-runner-user-importer"
    allow_dependency_failure: true
    command: "buildkite-agent pipeline upload .buildkite/experimental-runner-user-continuation.yml"
