package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"go.yaml.in/yaml/v4"
)

const repository = "https://github.com/actions/cache.git"

// snapshotBranches hold cache-v2-capable history. The releases/v1,
// releases/v2, and releases/v3-beta branches only bundle cache-v1 clients.
var snapshotBranches = []string{"main", "releases/v5"}

// entryPoints are the action directories the integration catalog admits.
var entryPoints = []string{"", "restore", "save"}

// cacheV2Markers must all appear in every bundle an admitted entry point
// runs. The runtime selects cache v2 with ACTIONS_CACHE_SERVICE_V2, routes
// traffic through ACTIONS_RESULTS_URL, and substitutes a .localhost
// GITHUB_SERVER_URL so the client's GHES check does not force cache v1.
var cacheV2Markers = []string{"ACTIONS_CACHE_SERVICE_V2", "ACTIONS_RESULTS_URL", ".LOCALHOST"}

var supportedRuntimes = map[string]bool{"node16": true, "node20": true, "node24": true}

var clientVersionPattern = regexp.MustCompile(`"name":"@actions/cache","version":"([^"]+)"`)

type actionManifest struct {
	Runs struct {
		Using string `yaml:"using"`
		Main  string `yaml:"main"`
		Post  string `yaml:"post"`
	} `yaml:"runs"`
}

type contract struct {
	Client              string
	Root, Restore, Save bool
}

func main() {
	output := "cache_profiles_generated.go"
	if len(os.Args) > 2 {
		fatalf("usage: go run ./cmd/generate-cache-profiles [output]")
	}
	if len(os.Args) == 2 {
		output = os.Args[1]
	}

	checkout, err := os.MkdirTemp("", "buildkite-gha-cache-profiles-")
	if err != nil {
		fatalf("create temporary checkout: %v", err)
	}
	defer func() { _ = os.RemoveAll(checkout) }()
	run(checkout, "git", "init", "--quiet")
	run(checkout, "git", "remote", "add", "origin", repository)
	refspecs := []string{"--quiet", "--no-tags", "origin", "+refs/tags/*:refs/tags/*"}
	for _, branch := range snapshotBranches {
		refspecs = append(refspecs, "+refs/heads/"+branch+":refs/remotes/origin/"+branch)
	}
	run(checkout, "git", append([]string{"fetch"}, refspecs...)...)

	tips := make(map[string]string, len(snapshotBranches))
	for _, branch := range snapshotBranches {
		tips[branch] = gitOutput(checkout, "rev-parse", "refs/remotes/origin/"+branch+"^{commit}")
	}
	commits := strings.Fields(gitOutput(checkout, "rev-list", "--all"))
	contracts := make(map[string]contract)
	for _, commit := range commits {
		profile, ok := snapshotCommit(checkout, commit)
		if ok {
			contracts[commit] = profile
		}
	}

	profilesByContract := map[contract]string{}
	uniqueContracts := make([]contract, 0)
	for _, profile := range contracts {
		if _, ok := profilesByContract[profile]; ok {
			continue
		}
		uniqueContracts = append(uniqueContracts, profile)
		profilesByContract[profile] = ""
	}
	sort.Slice(uniqueContracts, func(i, j int) bool {
		return contractKey(uniqueContracts[i]) < contractKey(uniqueContracts[j])
	})
	for i, profile := range uniqueContracts {
		profilesByContract[profile] = fmt.Sprintf("cacheProfile%02d", i+1)
	}

	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by internal/action/integration/cmd/generate-cache-profiles; DO NOT EDIT.")
	fmt.Fprintln(&generated, "\npackage integration")
	fmt.Fprintf(&generated, "\nconst cacheMainSnapshotCommit = %q\n", tips["main"])
	fmt.Fprintln(&generated, "\nvar cacheSnapshotTips = map[string]string{")
	for _, branch := range snapshotBranches {
		fmt.Fprintf(&generated, "\t%q: %q,\n", branch, tips[branch])
	}
	fmt.Fprintln(&generated, "}")
	fmt.Fprintln(&generated, "\nvar (")
	for _, profile := range uniqueContracts {
		fmt.Fprintf(&generated, "\t%s = cacheContract{client: %q, root: %t, restore: %t, save: %t}\n",
			profilesByContract[profile], profile.Client, profile.Root, profile.Restore, profile.Save)
	}
	fmt.Fprintln(&generated, ")")
	fmt.Fprintln(&generated, "\nvar cacheCommitContracts = map[string]cacheContract{")
	commitKeys := sortedKeys(contracts)
	for _, commit := range commitKeys {
		fmt.Fprintf(&generated, "\t%q: %s,\n", commit, profilesByContract[contracts[commit]])
	}
	fmt.Fprintln(&generated, "}")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(filepath.Clean(output), formatted, 0o644); err != nil {
		fatalf("write generated source: %v", err)
	}
}

// snapshotCommit records which entry points of one immutable commit run
// cache-v2 bundles. Every admitted bundle must embed the same @actions/cache
// client version; commits with no admitted entry point are omitted.
func snapshotCommit(checkout, commit string) (contract, bool) {
	var profile contract
	clients := map[string]bool{}
	admitted := false
	for _, entryPoint := range entryPoints {
		client, ok := snapshotEntryPoint(checkout, commit, entryPoint)
		if !ok {
			continue
		}
		admitted = true
		clients[client] = true
		switch entryPoint {
		case "":
			profile.Root = true
		case "restore":
			profile.Restore = true
		case "save":
			profile.Save = true
		}
	}
	if !admitted || len(clients) != 1 {
		return contract{}, false
	}
	for client := range clients {
		profile.Client = client
	}
	return profile, true
}

func snapshotEntryPoint(checkout, commit, entryPoint string) (string, bool) {
	source, err := gitShow(checkout, commit, path.Join(entryPoint, "action.yml"))
	if err != nil {
		source, err = gitShow(checkout, commit, path.Join(entryPoint, "action.yaml"))
	}
	if err != nil {
		return "", false
	}
	var manifest actionManifest
	if yaml.Unmarshal(source, &manifest) != nil || !supportedRuntimes[manifest.Runs.Using] || manifest.Runs.Main == "" {
		return "", false
	}
	bundles := []string{path.Join(entryPoint, manifest.Runs.Main)}
	if entryPoint == "" {
		if manifest.Runs.Post == "" {
			return "", false
		}
		bundles = append(bundles, path.Join(entryPoint, manifest.Runs.Post))
	}
	client := ""
	for _, bundle := range bundles {
		bundleClient, ok := cacheV2Bundle(checkout, commit, bundle)
		if !ok || client != "" && client != bundleClient {
			return "", false
		}
		client = bundleClient
	}
	return client, true
}

// cacheV2Bundle reports the single @actions/cache client version embedded in a
// bundle that carries every cache-v2 marker.
func cacheV2Bundle(checkout, commit, bundle string) (string, bool) {
	if strings.HasPrefix(bundle, "../") {
		return "", false
	}
	source, err := gitShow(checkout, commit, bundle)
	if err != nil {
		return "", false
	}
	for _, marker := range cacheV2Markers {
		if !bytes.Contains(source, []byte(marker)) {
			return "", false
		}
	}
	client := ""
	for _, match := range clientVersionPattern.FindAllSubmatch(source, -1) {
		version := string(match[1])
		if client != "" && client != version {
			return "", false
		}
		client = version
	}
	return client, client != ""
}

func gitShow(checkout, commit, file string) ([]byte, error) {
	return exec.Command("git", "-C", checkout, "show", commit+":"+file).Output()
}

func sortedKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func contractKey(profile contract) string {
	return fmt.Sprintf("%s\x00%t\x00%t\x00%t", profile.Client, profile.Root, profile.Restore, profile.Save)
}

func gitOutput(directory string, args ...string) string {
	command := exec.Command("git", append([]string{"-C", directory}, args...)...)
	output, err := command.Output()
	if err != nil {
		fatalf("git %s: %v", strings.Join(args, " "), err)
	}
	return strings.TrimSpace(string(output))
}

func run(directory, name string, args ...string) {
	command := exec.Command(name, args...)
	command.Dir = directory
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		fatalf("%s %s: %v", name, strings.Join(args, " "), err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
