package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"go.yaml.in/yaml/v4"
)

const repository = "https://github.com/actions/checkout.git"

var snapshotBranches = []string{"main", "master", "releases/v1", "releases/v2", "releases/v3", "releases/v4", "releases/v5", "releases/v6"}

type actionManifest struct {
	Inputs  map[string]yaml.Node `yaml:"inputs"`
	Outputs map[string]yaml.Node `yaml:"outputs"`
	Runs    struct {
		Plugin string `yaml:"plugin"`
	} `yaml:"runs"`
}

type contract struct {
	Inputs       string
	FullHistory  bool
	RefOutput    bool
	CommitOutput bool
}

func main() {
	output := "checkout_profiles_generated.go"
	if len(os.Args) > 2 {
		fatalf("usage: go run ./cmd/generate-checkout-profiles [output]")
	}
	if len(os.Args) == 2 {
		output = os.Args[1]
	}

	checkout, err := os.MkdirTemp("", "buildkite-gha-checkout-profiles-")
	if err != nil {
		fatalf("create temporary checkout: %v", err)
	}
	defer func() { _ = os.RemoveAll(checkout) }()
	run(checkout, "git", "init", "--quiet")
	run(checkout, "git", "remote", "add", "origin", repository)
	refspecs := []string{"--quiet", "--no-tags", "origin", "+refs/tags/*:refs/tags/*"}
	for _, branch := range snapshotBranches {
		refspecs = append(refspecs, "+refs/heads/"+branch+":refs/remotes/origin/"+branch)
	}
	run(checkout, "git", append([]string{"fetch"}, refspecs...)...)

	tips := make(map[string]string, len(snapshotBranches))
	for _, branch := range snapshotBranches {
		tips[branch] = gitOutput(checkout, "rev-parse", "refs/remotes/origin/"+branch+"^{commit}")
	}
	commits := strings.Fields(gitOutput(checkout, "rev-list", "--all"))
	contracts := make(map[string]contract)
	for _, commit := range commits {
		source, err := exec.Command("git", "-C", checkout, "show", commit+":action.yml").Output()
		if err != nil {
			source, err = exec.Command("git", "-C", checkout, "show", commit+":action.yaml").Output()
		}
		if err != nil {
			continue
		}
		var manifest actionManifest
		if yaml.Unmarshal(source, &manifest) != nil {
			continue
		}
		outputs := sortedKeys(manifest.Outputs)
		if len(outputs) != 0 && (len(outputs) != 2 || outputs[0] != "commit" || outputs[1] != "ref") {
			continue
		}
		inputs := sortedKeys(manifest.Inputs)
		contracts[commit] = contract{
			Inputs:       strings.Join(inputs, ","),
			FullHistory:  manifest.Runs.Plugin != "",
			RefOutput:    contains(outputs, "ref"),
			CommitOutput: contains(outputs, "commit"),
		}
	}

	profilesByContract := map[contract]string{}
	uniqueContracts := make([]contract, 0)
	for _, profile := range contracts {
		if _, ok := profilesByContract[profile]; ok {
			continue
		}
		uniqueContracts = append(uniqueContracts, profile)
		profilesByContract[profile] = ""
	}
	sort.Slice(uniqueContracts, func(i, j int) bool {
		return contractKey(uniqueContracts[i]) < contractKey(uniqueContracts[j])
	})
	for i, profile := range uniqueContracts {
		profilesByContract[profile] = fmt.Sprintf("checkoutProfile%02d", i+1)
	}

	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by internal/action/integration/cmd/generate-checkout-profiles; DO NOT EDIT.")
	fmt.Fprintln(&generated, "\npackage integration")
	fmt.Fprintf(&generated, "\nconst checkoutMainSnapshotCommit = %q\n", tips["main"])
	fmt.Fprintln(&generated, "\nvar checkoutSnapshotTips = map[string]string{")
	for _, branch := range snapshotBranches {
		fmt.Fprintf(&generated, "\t%q: %q,\n", branch, tips[branch])
	}
	fmt.Fprintln(&generated, "}")
	fmt.Fprintln(&generated, "\nvar (")
	for _, profile := range uniqueContracts {
		fmt.Fprintf(&generated, "\t%s = checkoutContract{inputs: %q, fullHistory: %t, refOutput: %t, commitOutput: %t}\n",
			profilesByContract[profile], profile.Inputs, profile.FullHistory, profile.RefOutput, profile.CommitOutput)
	}
	fmt.Fprintln(&generated, ")")
	fmt.Fprintln(&generated, "\nvar checkoutCommitContracts = map[string]checkoutContract{")
	commitKeys := sortedKeys(contracts)
	for _, commit := range commitKeys {
		fmt.Fprintf(&generated, "\t%q: %s,\n", commit, profilesByContract[contracts[commit]])
	}
	fmt.Fprintln(&generated, "}")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(filepath.Clean(output), formatted, 0o644); err != nil {
		fatalf("write generated source: %v", err)
	}
}

func sortedKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, strings.ToLower(key))
	}
	sort.Strings(keys)
	return keys
}

func contains(values []string, target string) bool {
	index := sort.SearchStrings(values, target)
	return index < len(values) && values[index] == target
}

func contractKey(profile contract) string {
	return fmt.Sprintf("%s\x00%t\x00%t\x00%t", profile.Inputs, profile.FullHistory, profile.RefOutput, profile.CommitOutput)
}

func gitOutput(directory string, args ...string) string {
	command := exec.Command("git", append([]string{"-C", directory}, args...)...)
	output, err := command.Output()
	if err != nil {
		fatalf("git %s: %v", strings.Join(args, " "), err)
	}
	return strings.TrimSpace(string(output))
}

func run(directory, name string, args ...string) {
	command := exec.Command(name, args...)
	command.Dir = directory
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		fatalf("%s %s: %v", name, strings.Join(args, " "), err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
